# число строк в пузырьке чата
maxBubbleHeight: 3

# максимальная ширина пузырьков чата, более длинные слова не будут обрезаны и по-прежнему будут отображаться целиком в одной строке
maxBubbleWidth: 15

# тики для ожидания между пузырьками чата, по умолчанию 5 тиков (250 мс)
bubblesInterval: 5

# символов в минуту, учитывая в среднем 5 символов в слове (4 буквы + 1 пробел)
readSpeed: 800

# время, чтобы заметить сообщение и начать читать
handicapChars: 10

# отображать ники в табе и при вводе команд в чате, false - не отображать, true - отображать
displayNames: false

# формат чата, не трогать
chatFormat: EL